package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmOwnerRecord<M extends BaseCrmOwnerRecord<M>> extends Model<M> implements IBean {

	public void setRecordId(Integer recordId) {
		set("record_id", recordId);
	}

	public Integer getRecordId() {
		return getInt("record_id");
	}

	public void setTypeId(Integer typeId) {
		set("type_id", typeId);
	}

	public Integer getTypeId() {
		return getInt("type_id");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return getInt("type");
	}

	public void setPreOwnerUserId(Integer preOwnerUserId) {
		set("pre_owner_user_id", preOwnerUserId);
	}

	public Integer getPreOwnerUserId() {
		return getInt("pre_owner_user_id");
	}

	public void setPostOwnerUserId(Integer postOwnerUserId) {
		set("post_owner_user_id", postOwnerUserId);
	}

	public Integer getPostOwnerUserId() {
		return getInt("post_owner_user_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
