package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmCustomer<M extends BaseCrmCustomer<M>> extends Model<M> implements IBean {

	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}
	
	public java.lang.Integer getCustomerId() {
		return getInt("customer_id");
	}

	public void setCustomerName(java.lang.String customerName) {
		set("customer_name", customerName);
	}
	
	public java.lang.String getCustomerName() {
		return getStr("customer_name");
	}

	public void setFollowup(java.lang.Integer followup) {
		set("followup", followup);
	}
	
	public java.lang.Integer getFollowup() {
		return getInt("followup");
	}

	public void setIsLock(java.lang.Integer isLock) {
		set("is_lock", isLock);
	}
	
	public java.lang.Integer getIsLock() {
		return getInt("is_lock");
	}

	public void setNextTime(java.util.Date nextTime) {
		set("next_time", nextTime);
	}
	
	public java.util.Date getNextTime() {
		return get("next_time");
	}

	public void setDealStatus(java.lang.Integer dealStatus) {
		set("deal_status", dealStatus);
	}
	
	public java.lang.Integer getDealStatus() {
		return getInt("deal_status");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}
	
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}

	public void setWebsite(java.lang.String website) {
		set("website", website);
	}
	
	public java.lang.String getWebsite() {
		return getStr("website");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setCreateUserId(java.lang.Long createUserId) {
		set("create_user_id", createUserId);
	}
	
	public java.lang.Long getCreateUserId() {
		return getLong("create_user_id");
	}

	public void setOwnerUserId(java.lang.Long ownerUserId) {
		set("owner_user_id", ownerUserId);
	}
	
	public java.lang.Long getOwnerUserId() {
		return getLong("owner_user_id");
	}

	public void setRoUserId(java.lang.String roUserId) {
		set("ro_user_id", roUserId);
	}
	
	public java.lang.String getRoUserId() {
		return getStr("ro_user_id");
	}

	public void setRwUserId(java.lang.String rwUserId) {
		set("rw_user_id", rwUserId);
	}
	
	public java.lang.String getRwUserId() {
		return getStr("rw_user_id");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setLocation(java.lang.String location) {
		set("location", location);
	}
	
	public java.lang.String getLocation() {
		return getStr("location");
	}

	public void setDetailAddress(java.lang.String detailAddress) {
		set("detail_address", detailAddress);
	}
	
	public java.lang.String getDetailAddress() {
		return getStr("detail_address");
	}

	public void setLng(java.lang.String lng) {
		set("lng", lng);
	}
	
	public java.lang.String getLng() {
		return getStr("lng");
	}

	public void setLat(java.lang.String lat) {
		set("lat", lat);
	}
	
	public java.lang.String getLat() {
		return getStr("lat");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setBatchId(java.lang.String batchId) {
		set("batch_id", batchId);
	}
	
	public java.lang.String getBatchId() {
		return getStr("batch_id");
	}

	public M setLastContent(java.lang.String lastContent) {
		set("last_content", lastContent);
		return (M)this;
	}

	public java.lang.String getLastContent() {
		return getStr("last_content");
	}

}
