package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmBusinessProduct<M extends BaseCrmBusinessProduct<M>> extends Model<M> implements IBean {

	public void setRId(Integer rId) {
		set("r_id", rId);
	}

	public Integer getRId() {
		return getInt("r_id");
	}

	public void setBusinessId(Integer businessId) {
		set("business_id", businessId);
	}

	public Integer getBusinessId() {
		return getInt("business_id");
	}

	public void setProductId(Integer productId) {
		set("product_id", productId);
	}

	public Integer getProductId() {
		return getInt("product_id");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setSalesPrice(java.math.BigDecimal salesPrice) {
		set("sales_price", salesPrice);
	}

	public java.math.BigDecimal getSalesPrice() {
		return get("sales_price");
	}

	public void setNum(Integer num) {
		set("num", num);
	}

	public Integer getNum() {
		return getInt("num");
	}

	public void setDiscount(Integer discount) {
		set("discount", discount);
	}

	public Integer getDiscount() {
		return getInt("discount");
	}

	public void setSubtotal(java.math.BigDecimal subtotal) {
		set("subtotal", subtotal);
	}

	public java.math.BigDecimal getSubtotal() {
		return get("subtotal");
	}

	public void setUnit(String unit) {
		set("unit", unit);
	}

	public String getUnit() {
		return getStr("unit");
	}

}
