package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmCustomerSetting<M extends BaseCrmCustomerSetting<M>> extends Model<M> implements IBean {

	public void setSettingId(java.lang.Integer settingId) {
		set("setting_id", settingId);
	}
	
	public java.lang.Integer getSettingId() {
		return getInt("setting_id");
	}

	public void setSettingName(java.lang.String settingName) {
		set("setting_name", settingName);
	}
	
	public java.lang.String getSettingName() {
		return getStr("setting_name");
	}

	public void setCustomerNum(java.lang.Integer customerNum) {
		set("customer_num", customerNum);
	}
	
	public java.lang.Integer getCustomerNum() {
		return getInt("customer_num");
	}

	public void setCustomerDeal(java.lang.Integer customerDeal) {
		set("customer_deal", customerDeal);
	}
	
	public java.lang.Integer getCustomerDeal() {
		return getInt("customer_deal");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
