package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.math.BigDecimal;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmBusiness<M extends BaseCrmBusiness<M>> extends Model<M> implements IBean {

	public void setBusinessId(Integer businessId) {
		set("business_id", businessId);
	}

	public Integer getBusinessId() {
		return getInt("business_id");
	}

	public void setTypeId(Integer typeId) {
		set("type_id", typeId);
	}

	public Integer getTypeId() {
		return getInt("type_id");
	}

	public void setStatusId(Integer statusId) {
		set("status_id", statusId);
	}

	public Integer getStatusId() {
		return getInt("status_id");
	}

	public void setNextTime(java.util.Date nextTime) {
		set("next_time", nextTime);
	}

	public java.util.Date getNextTime() {
		return get("next_time");
	}

	public void setCustomerId(Integer customerId) {
		set("customer_id", customerId);
	}

	public Integer getCustomerId() {
		return getInt("customer_id");
	}

	public void setDealDate(java.util.Date dealDate) {
		set("deal_date", dealDate);
	}

	public java.util.Date getDealDate() {
		return get("deal_date");
	}

	public void setBusinessName(String businessName) {
		set("business_name", businessName);
	}

	public String getBusinessName() {
		return getStr("business_name");
	}

	public void setMoney(java.math.BigDecimal money) {
		set("money", money);
	}

	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	public void setDiscountRate(java.math.BigDecimal discountRate) {
		set("discount_rate", discountRate);
	}

	public java.math.BigDecimal getDiscountRate() {
		return get("discount_rate");
	}

	public void setTotalPrice(String totalPrice) {
		set("total_price", new BigDecimal(totalPrice));
	}

	public java.math.BigDecimal getTotalPrice() {
		return get("total_price");
	}

	public void setRemark(String remark){
		set("remark", remark);
	}

	public String getRemark(){
		return getStr("remark");
	}

	public void setCreateUserId(Integer createUserId) {
		set("create_user_id", createUserId);
	}

	public Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public void setOwnerUserId(Integer ownerUserId) {
		set("owner_user_id", ownerUserId);
	}

	public Integer getOwnerUserId() {
		return getInt("owner_user_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setBatchId(String batchId) {
		set("batch_id", batchId);
	}

	public String getBatchId() {
		return getStr("batch_id");
	}

	public void setRoUserId(String roUserId) {
		set("ro_user_id", roUserId);
	}

	public String getRoUserId() {
		return getStr("ro_user_id");
	}

	public void setRwUserId(String rwUserId) {
		set("rw_user_id", rwUserId);
	}

	public String getRwUserId() {
		return getStr("rw_user_id");
	}

	public void setIsEnd(Integer isEnd){
		set("is_end",isEnd);
	}

	public Integer getIsEnd(){
		return getInt("is_end");
	}

	public void setStatusRemark(String statusRemark){
		set("status_remark", statusRemark);
	}

	public String getStatusRemark(){
		return getStr("status_remark");
	}
}
