package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmContract<M extends BaseCrmContract<M>> extends Model<M> implements IBean {

	public void setContractId(java.lang.Integer contractId) {
		set("contract_id", contractId);
	}
	
	public java.lang.Integer getContractId() {
		return getInt("contract_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}
	
	public java.lang.Integer getCustomerId() {
		return getInt("customer_id");
	}

	public void setBusinessId(java.lang.Integer businessId) {
		set("business_id", businessId);
	}
	
	public java.lang.Integer getBusinessId() {
		return getInt("business_id");
	}

	public void setCheckStatus(java.lang.Integer checkStatus) {
		set("check_status", checkStatus);
	}
	
	public java.lang.Integer getCheckStatus() {
		return getInt("check_status");
	}

	public void setExamineRecordId(java.lang.Integer examineRecordId) {
		set("examine_record_id", examineRecordId);
	}
	
	public java.lang.Integer getExamineRecordId() {
		return getInt("examine_record_id");
	}

	public void setOrderDate(java.util.Date orderDate) {
		set("order_date", orderDate);
	}
	
	public java.util.Date getOrderDate() {
		return get("order_date");
	}

	public void setCreateUserId(java.lang.Long createUserId) {
		set("create_user_id", createUserId);
	}
	
	public java.lang.Long getCreateUserId() {
		return getLong("create_user_id");
	}

	public void setOwnerUserId(java.lang.Long ownerUserId) {
		set("owner_user_id", ownerUserId);
	}
	
	public java.lang.Long getOwnerUserId() {
		return getLong("owner_user_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setNum(java.lang.String num) {
		set("num", num);
	}
	
	public java.lang.String getNum() {
		return getStr("num");
	}

	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}
	
	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}
	
	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public void setMoney(java.math.BigDecimal money) {
		set("money", money);
	}
	
	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	public void setDiscountRate(java.math.BigDecimal discountRate) {
		set("discount_rate", discountRate);
	}
	
	public java.math.BigDecimal getDiscountRate() {
		return get("discount_rate");
	}

	public void setTotalPrice(java.math.BigDecimal totalPrice) {
		set("total_price", totalPrice);
	}
	
	public java.math.BigDecimal getTotalPrice() {
		return get("total_price");
	}

	public void setTypes(java.lang.String types) {
		set("types", types);
	}
	
	public java.lang.String getTypes() {
		return getStr("types");
	}

	public void setPaymentType(java.lang.String paymentType) {
		set("payment_type", paymentType);
	}
	
	public java.lang.String getPaymentType() {
		return getStr("payment_type");
	}

	public void setBatchId(java.lang.String batchId) {
		set("batch_id", batchId);
	}
	
	public java.lang.String getBatchId() {
		return getStr("batch_id");
	}

	public void setRoUserId(java.lang.String roUserId) {
		set("ro_user_id", roUserId);
	}
	
	public java.lang.String getRoUserId() {
		return getStr("ro_user_id");
	}

	public void setRwUserId(java.lang.String rwUserId) {
		set("rw_user_id", rwUserId);
	}
	
	public java.lang.String getRwUserId() {
		return getStr("rw_user_id");
	}

	public void setContactsId(java.lang.Integer contactsId) {
		set("contacts_id", contactsId);
	}
	
	public java.lang.Integer getContactsId() {
		return getInt("contacts_id");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setCompanyUserId(java.lang.Integer companyUserId) {
		set("company_user_id", companyUserId);
	}
	
	public java.lang.Integer getCompanyUserId() {
		return getInt("company_user_id");
	}

}
