package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmBusiness<M extends BaseCrmBusiness<M>> extends Model<M> implements IBean {

	public void setBusinessId(java.lang.Integer businessId) {
		set("business_id", businessId);
	}
	
	public java.lang.Integer getBusinessId() {
		return getInt("business_id");
	}

	public void setTypeId(java.lang.Integer typeId) {
		set("type_id", typeId);
	}
	
	public java.lang.Integer getTypeId() {
		return getInt("type_id");
	}

	public void setStatusId(java.lang.Integer statusId) {
		set("status_id", statusId);
	}
	
	public java.lang.Integer getStatusId() {
		return getInt("status_id");
	}

	public void setNextTime(java.util.Date nextTime) {
		set("next_time", nextTime);
	}
	
	public java.util.Date getNextTime() {
		return get("next_time");
	}

	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}
	
	public java.lang.Integer getCustomerId() {
		return getInt("customer_id");
	}

	public void setDealDate(java.util.Date dealDate) {
		set("deal_date", dealDate);
	}
	
	public java.util.Date getDealDate() {
		return get("deal_date");
	}

	public void setBusinessName(java.lang.String businessName) {
		set("business_name", businessName);
	}
	
	public java.lang.String getBusinessName() {
		return getStr("business_name");
	}

	public void setMoney(java.math.BigDecimal money) {
		set("money", money);
	}
	
	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	public void setDiscountRate(java.math.BigDecimal discountRate) {
		set("discount_rate", discountRate);
	}
	
	public java.math.BigDecimal getDiscountRate() {
		return get("discount_rate");
	}

	public void setTotalPrice(java.math.BigDecimal totalPrice) {
		set("total_price", totalPrice);
	}
	
	public java.math.BigDecimal getTotalPrice() {
		return get("total_price");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setCreateUserId(java.lang.Long createUserId) {
		set("create_user_id", createUserId);
	}
	
	public java.lang.Long getCreateUserId() {
		return getLong("create_user_id");
	}

	public void setOwnerUserId(java.lang.Long ownerUserId) {
		set("owner_user_id", ownerUserId);
	}
	
	public java.lang.Long getOwnerUserId() {
		return getLong("owner_user_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setBatchId(java.lang.String batchId) {
		set("batch_id", batchId);
	}
	
	public java.lang.String getBatchId() {
		return getStr("batch_id");
	}

	public void setRoUserId(java.lang.String roUserId) {
		set("ro_user_id", roUserId);
	}
	
	public java.lang.String getRoUserId() {
		return getStr("ro_user_id");
	}

	public void setRwUserId(java.lang.String rwUserId) {
		set("rw_user_id", rwUserId);
	}
	
	public java.lang.String getRwUserId() {
		return getStr("rw_user_id");
	}

	public void setIsEnd(java.lang.Integer isEnd) {
		set("is_end", isEnd);
	}
	
	public java.lang.Integer getIsEnd() {
		return getInt("is_end");
	}

	public void setStatusRemark(java.lang.String statusRemark) {
		set("status_remark", statusRemark);
	}
	
	public java.lang.String getStatusRemark() {
		return getStr("status_remark");
	}

}
