package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmReceivablesPlan<M extends BaseCrmReceivablesPlan<M>> extends Model<M> implements IBean {

	public M setPlanId(Integer planId) {
		set("plan_id", planId);
		return (M)this;
	}

	public Integer getPlanId() {
		return getInt("plan_id");
	}

	public M setNum(String num) {
		set("num", num);
		return (M)this;
	}

	public String getNum() {
		return getStr("num");
	}

	public M setReceivablesId(Integer receivablesId) {
		set("receivables_id", receivablesId);
		return (M)this;
	}

	public Integer getReceivablesId() {
		return getInt("receivables_id");
	}

	public M setStatus(Integer status) {
		set("status", status);
		return (M)this;
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public M setMoney(java.math.BigDecimal money) {
		set("money", money);
		return (M)this;
	}

	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	public M setReturnDate(java.util.Date returnDate) {
		set("return_date", returnDate);
		return (M)this;
	}

	public java.util.Date getReturnDate() {
		return get("return_date");
	}

	public M setReturnType(String returnType) {
		set("return_type", returnType);
		return (M)this;
	}

	public String getReturnType() {
		return getStr("return_type");
	}

	public M setRemind(Integer remind) {
		set("remind", remind);
		return (M)this;
	}

	public Integer getRemind() {
		return getInt("remind");
	}

	public M setRemindDate(java.util.Date remindDate) {
		set("remind_date", remindDate);
		return (M)this;
	}

	public java.util.Date getRemindDate() {
		return get("remind_date");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

	public M setCreateUserId(Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}

	public Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public M setOwnerUserId(Integer ownerUserId) {
		set("owner_user_id", ownerUserId);
		return (M)this;
	}

	public Integer getOwnerUserId() {
		return getInt("owner_user_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setFileBatch(String fileBatch) {
		set("file_batch", fileBatch);
		return (M)this;
	}

	public String getFileBatch() {
		return getStr("file_batch");
	}

	public M setContractId(Integer contractId) {
		set("contract_id", contractId);
		return (M)this;
	}

	public Integer getContractId() {
		return getInt("contract_id");
	}

	public M setCustomerId(Integer customerId) {
		set("customer_id", customerId);
		return (M)this;
	}

	public Integer getCustomerId() {
		return getInt("customer_id");
	}

}
