package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.math.BigDecimal;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmContract<M extends BaseCrmContract<M>> extends Model<M> implements IBean {

	public void setContractId(Integer contractId) {
		set("contract_id", contractId);
	}

	public Integer getContractId() {
		return getInt("contract_id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return getStr("name");
	}

	public void setCustomerId(Integer customerId) {
		set("customer_id", customerId);
	}

	public Integer getCustomerId() {
		return getInt("customer_id");
	}

	public void setBusinessId(Integer businessId) {
		set("business_id", businessId);
	}

	public Integer getBusinessId() {
		return getInt("business_id");
	}

	public void setCheckStatus(Integer checkStatus) {
		set("check_status", checkStatus);
	}

	public Integer getCheckStatus() {
		return getInt("check_status");
	}

	public void setExamineRecordId(Integer examineRecordId) {
		set("examine_record_id", examineRecordId);
	}

	public Integer getExamineRecordId() {
		return getInt("examine_record_id");
	}

	public void setOrderDate(java.util.Date orderDate) {
		set("order_date", orderDate);
	}

	public java.util.Date getOrderDate() {
		return get("order_date");
	}

	public void setCreateUserId(Integer createUserId) {
		set("create_user_id", createUserId);
	}

	public Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public void setOwnerUserId(Integer ownerUserId) {
		set("owner_user_id", ownerUserId);
	}

	public Integer getOwnerUserId() {
		return getInt("owner_user_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setNum(String num) {
		set("num", num);
	}

	public String getNum() {
		return getStr("num");
	}

	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}

	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public void setMoney(java.math.BigDecimal money) {
		set("money", money);
	}

	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	public void setDiscountRate(java.math.BigDecimal discountRate) {
		set("discount_rate", discountRate);
	}

	public java.math.BigDecimal getDiscountRate() {
		return get("discount_rate");
	}

	public void setTotalPrice(String totalPrice) {
		set("total_price", new BigDecimal(totalPrice));
	}

	public java.math.BigDecimal getTotalPrice() {
		return get("total_price");
	}

	public void setTypes(String types) {
		set("types", types);
	}

	public String getTypes() {
		return getStr("types");
	}

	public void setPaymentType(String paymentType) {
		set("payment_type", paymentType);
	}

	public String getPaymentType() {
		return getStr("payment_type");
	}

	public void setBatchId(String batchId) {
		set("batch_id", batchId);
	}

	public String getBatchId() {
		return getStr("batch_id");
	}
	//审核时间(非数据库字段)
	public Integer getCheckTime() {
		return getInt("check_time");
	}

	public void setCheckTime(Integer checkTime) {
		set("check_time", checkTime);
	}
	//审核人名称(非数据库字段)
	public void setUsername(String username) {
		set("username", username);
	}

	public String getUsername() {
		return getStr("username");
	}

	public void setRoUserId(String roUserId) {
		set("ro_user_id", roUserId);
	}

	public String getRoUserId() {
		return getStr("ro_user_id");
	}

	public void setRwUserId(String rwUserId) {
		set("rw_user_id", rwUserId);
	}

	public String getRwUserId() {
		return getStr("rw_user_id");
	}
	public void setContactsId(Integer contactsId) {
		set("contacts_id", contactsId);
	}

	public Integer getContactsId() {
		return getInt("contacts_id");
	}
	public void setCompanyUserId(Integer companyUserId) {
		set("company_user_id", companyUserId);
	}

	public Integer getCompanyUserId() {
		return getInt("company_user_id");
	}
	public String getRemark() {
		return getStr("remark");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}

}
