package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmReceivables<M extends BaseCrmReceivables<M>> extends Model<M> implements IBean {

	public void setReceivablesId(Integer receivablesId) {
		set("receivables_id", receivablesId);
	}

	public Integer getReceivablesId() {
		return getInt("receivables_id");
	}

	public void setNumber(String number) {
		set("number", number);
	}

	public String getNumber() {
		return getStr("number");
	}

	public void setPlanId(Integer planId) {
		set("plan_id", planId);
	}

	public Integer getPlanId() {
		return getInt("plan_id");
	}

	public void setCustomerId(Integer customerId) {
		set("customer_id", customerId);
	}

	public Integer getCustomerId() {
		return getInt("customer_id");
	}

	public void setContractId(Integer contractId) {
		set("contract_id", contractId);
	}

	public Integer getContractId() {
		return getInt("contract_id");
	}

	public void setCheckStatus(Integer checkStatus) {
		set("check_status", checkStatus);
	}

	public Integer getCheckStatus() {
		return getInt("check_status");
	}

	public void setExamineRecordId(Integer examineRecordId) {
		set("examine_record_id", examineRecordId);
	}

	public Integer getExamineRecordId() {
		return getInt("examine_record_id");
	}

	public void setReturnTime(java.util.Date returnTime) {
		set("return_time", returnTime);
	}

	public java.util.Date getReturnTime() {
		return get("return_time");
	}

	public void setReturnType(String returnType) {
		set("return_type", returnType);
	}

	public String getReturnType() {
		return getStr("return_type");
	}

	public void setMoney(java.math.BigDecimal money) {
		set("money", money);
	}

	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}

	public String getRemark() {
		return getStr("remark");
	}

	public void setCreateUserId(Integer createUserId) {
		set("create_user_id", createUserId);
	}

	public Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public void setOwnerUserId(Integer ownerUserId) {
		set("owner_user_id", ownerUserId);
	}

	public Integer getOwnerUserId() {
		return getInt("owner_user_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}

	public String getRemarks() {
		return getStr("remarks");
	}
	//审核时间(非数据库字段)
	public Integer getCheckTime() {
		return getInt("check_time");
	}

	public void setCheckTime(Integer checkTime) {
		set("check_time", checkTime);
	}
	//审核人名称(非数据库字段)
	public void setUsername(String username) {
		set("username", username);
	}

	public String getUsername() {
		return getStr("username");
	}
	//合同名称(非数据库字段)
	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return getStr("name");
	}

	public void setBatchId(String batchId) {
		set("batch_id", batchId);
	}

	public String getBatchId() {
		return getStr("batch_id");
	}
}
