package com.kakarote.crm9.erp.work.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWork<M extends BaseWork<M>> extends Model<M> implements IBean {

	public void setWorkId(java.lang.Integer workId) {
		set("work_id", workId);
	}
	
	public java.lang.Integer getWorkId() {
		return getInt("work_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUserId(java.lang.Long createUserId) {
		set("create_user_id", createUserId);
	}
	
	public java.lang.Long getCreateUserId() {
		return getLong("create_user_id");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setColor(java.lang.String color) {
		set("color", color);
	}
	
	public java.lang.String getColor() {
		return getStr("color");
	}

	public void setIsOpen(java.lang.Integer isOpen) {
		set("is_open", isOpen);
	}
	
	public java.lang.Integer getIsOpen() {
		return getInt("is_open");
	}

	public void setOwnerUserId(java.lang.String ownerUserId) {
		set("owner_user_id", ownerUserId);
	}
	
	public java.lang.String getOwnerUserId() {
		return getStr("owner_user_id");
	}

	public void setArchiveTime(java.util.Date archiveTime) {
		set("archive_time", archiveTime);
	}
	
	public java.util.Date getArchiveTime() {
		return get("archive_time");
	}

	public void setDeleteTime(java.util.Date deleteTime) {
		set("delete_time", deleteTime);
	}
	
	public java.util.Date getDeleteTime() {
		return get("delete_time");
	}

	public void setBatchId(java.lang.String batchId) {
		set("batch_id", batchId);
	}
	
	public java.lang.String getBatchId() {
		return getStr("batch_id");
	}

}
