package com.kakarote.crm9.erp.work.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTask<M extends BaseTask<M>> extends Model<M> implements IBean {

	public void setTaskId(java.lang.Integer taskId) {
		set("task_id", taskId);
	}
	
	public java.lang.Integer getTaskId() {
		return getInt("task_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setCreateUserId(java.lang.Long createUserId) {
		set("create_user_id", createUserId);
	}
	
	public java.lang.Long getCreateUserId() {
		return getLong("create_user_id");
	}

	public void setMainUserId(java.lang.Long mainUserId) {
		set("main_user_id", mainUserId);
	}
	
	public java.lang.Long getMainUserId() {
		return getLong("main_user_id");
	}

	public void setOwnerUserId(java.lang.String ownerUserId) {
		set("owner_user_id", ownerUserId);
	}
	
	public java.lang.String getOwnerUserId() {
		return getStr("owner_user_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setClassId(java.lang.Integer classId) {
		set("class_id", classId);
	}
	
	public java.lang.Integer getClassId() {
		return getInt("class_id");
	}

	public void setLabelId(java.lang.String labelId) {
		set("label_id", labelId);
	}
	
	public java.lang.String getLabelId() {
		return getStr("label_id");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setPid(java.lang.Integer pid) {
		set("pid", pid);
	}
	
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}
	
	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public void setStopTime(java.util.Date stopTime) {
		set("stop_time", stopTime);
	}
	
	public java.util.Date getStopTime() {
		return get("stop_time");
	}

	public void setPriority(java.lang.Integer priority) {
		set("priority", priority);
	}
	
	public java.lang.Integer getPriority() {
		return getInt("priority");
	}

	public void setWorkId(java.lang.Integer workId) {
		set("work_id", workId);
	}
	
	public java.lang.Integer getWorkId() {
		return getInt("work_id");
	}

	public void setIsTop(java.lang.Integer isTop) {
		set("is_top", isTop);
	}
	
	public java.lang.Integer getIsTop() {
		return getInt("is_top");
	}

	public void setIsOpen(java.lang.Integer isOpen) {
		set("is_open", isOpen);
	}
	
	public java.lang.Integer getIsOpen() {
		return getInt("is_open");
	}

	public void setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
	}
	
	public java.lang.Integer getOrderNum() {
		return getInt("order_num");
	}

	public void setTopOrderNum(java.lang.Integer topOrderNum) {
		set("top_order_num", topOrderNum);
	}
	
	public java.lang.Integer getTopOrderNum() {
		return getInt("top_order_num");
	}

	public void setArchiveTime(java.util.Date archiveTime) {
		set("archive_time", archiveTime);
	}
	
	public java.util.Date getArchiveTime() {
		return get("archive_time");
	}

	public void setIshidden(java.lang.Integer ishidden) {
		set("ishidden", ishidden);
	}
	
	public java.lang.Integer getIshidden() {
		return getInt("ishidden");
	}

	public void setHiddenTime(java.util.Date hiddenTime) {
		set("hidden_time", hiddenTime);
	}
	
	public java.util.Date getHiddenTime() {
		return get("hidden_time");
	}

	public void setBatchId(java.lang.String batchId) {
		set("batch_id", batchId);
	}
	
	public java.lang.String getBatchId() {
		return getStr("batch_id");
	}

	public void setIsArchive(java.lang.Integer isArchive) {
		set("is_archive", isArchive);
	}
	
	public java.lang.Integer getIsArchive() {
		return getInt("is_archive");
	}

}
