package com.kakarote.crm9.erp.work.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWorkTaskLog<M extends BaseWorkTaskLog<M>> extends Model<M> implements IBean {

	public void setLogId(java.lang.Integer logId) {
		set("log_id", logId);
	}
	
	public java.lang.Integer getLogId() {
		return getInt("log_id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setTaskId(java.lang.Integer taskId) {
		set("task_id", taskId);
	}
	
	public java.lang.Integer getTaskId() {
		return getInt("task_id");
	}

	public void setWorkId(java.lang.Integer workId) {
		set("work_id", workId);
	}
	
	public java.lang.Integer getWorkId() {
		return getInt("work_id");
	}

}
