package com.kakarote.crm9.erp.work.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWorkRelation<M extends BaseWorkRelation<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setWorkId(Integer workId) {
		set("work_id", workId);
		return (M)this;
	}

	public Integer getWorkId() {
		return getInt("work_id");
	}

	public M setRelationId(Integer relationId) {
		set("relation_id", relationId);
		return (M)this;
	}

	public Integer getRelationId() {
		return getInt("relation_id");
	}

	public M setRelationType(Integer relationType) {
		set("relation_type", relationType);
		return (M)this;
	}

	public Integer getRelationType() {
		return getInt("relation_type");
	}

	public M setStatus(Integer status) {
		set("status", status);
		return (M)this;
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
