package com.kakarote.crm9.erp.work.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWork<M extends BaseWork<M>> extends Model<M> implements IBean {

	public void setWorkId(Integer workId) {
		set("work_id", workId);
	}

	public Integer getWorkId() {
		return getInt("work_id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return getStr("name");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUserId(Integer createUserId) {
		set("create_user_id", createUserId);
	}

	public Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public void setDescription(String description) {
		set("description", description);
	}

	public String getDescription() {
		return getStr("description");
	}

	public void setColor(String color) {
		set("color", color);
	}

	public String getColor() {
		return getStr("color");
	}

	public void setIsOpen(Integer isOpen) {
		set("is_open", isOpen);
	}

	public Integer getIsOpen() {
		return getInt("is_open");
	}

	public void setOwnerUserId(String ownerUserId) {
		set("owner_user_id", ownerUserId);
	}

	public String getOwnerUserId() {
		return getStr("owner_user_id");
	}

	public void setIshidden(Integer ishidden) {
		set("ishidden", ishidden);
	}

	public Integer getIshidden() {
		return getInt("ishidden");
	}

	public void setArchiveTime(java.util.Date archiveTime) {
		set("archive_time", archiveTime);
	}

	public java.util.Date getArchiveTime() {
		return get("archive_time");
	}

	public void setBatchId(String batchId) {
		set("batch_id", batchId);
	}

	public String getBatchId() {
		return getStr("batch_id");
	}

}
