package com.kakarote.crm9.erp.work.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTask<M extends BaseTask<M>> extends Model<M> implements IBean {

	public void setTaskId(Integer taskId) {
		set("task_id", taskId);
	}

	public Integer getTaskId() {
		return getInt("task_id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return getStr("name");
	}

	public void setCreateUserId(Integer createUserId) {
		set("create_user_id", createUserId);
	}

	public Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public void setMainUserId(Integer mainUserId) {
		set("main_user_id", mainUserId);
	}

	public Integer getMainUserId() {
		return getInt("main_user_id");
	}

	public void setOwnerUserId(String ownerUserId) {
		set("owner_user_id", ownerUserId);
	}

	public String getOwnerUserId() {
		return getStr("owner_user_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public void setClassId(Integer classId) {
		set("class_id", classId);
	}

	public Integer getClassId() {
		return getInt("class_id");
	}

	public void setLabelId(String labelId) {
		set("label_id", labelId);
	}

	public String getLabelId() {
		return getStr("label_id");
	}

	public void setDescription(String description) {
		set("description", description);
	}

	public String getDescription() {
		return getStr("description");
	}

	public void setPid(Integer pid) {
		set("pid", pid);
	}

	public Integer getPid() {
		return getInt("pid");
	}

	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}

	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public void setStopTime(java.util.Date stopTime) {
		set("stop_time", stopTime);
	}

	public java.util.Date getStopTime() {
		return get("stop_time");
	}

	public void setPriority(Integer priority) {
		set("priority", priority);
	}

	public Integer getPriority() {
		return getInt("priority");
	}

	public void setWorkId(Integer workId) {
		set("work_id", workId);
	}

	public Integer getWorkId() {
		return getInt("work_id");
	}

	public void setIsTop(Integer isTop) {
		set("is_top", isTop);
	}

	public Integer getIsTop() {
		return getInt("is_top");
	}

	public void setIsOpen(Integer isOpen) {
		set("is_open", isOpen);
	}

	public Integer getIsOpen() {
		return getInt("is_open");
	}

	public void setOrderNum(Integer orderNum) {
		set("order_num", orderNum);
	}

	public Integer getOrderNum() {
		return getInt("order_num");
	}

	public void setTopOrderNum(Integer topOrderNum) {
		set("top_order_num", topOrderNum);
	}

	public Integer getTopOrderNum() {
		return getInt("top_order_num");
	}

	public void setArchiveTime(java.util.Date archiveTime) {
		set("archive_time", archiveTime);
	}

	public java.util.Date getArchiveTime() {
		return get("archive_time");
	}

	public void setIshidden(Integer ishidden) {
		set("ishidden", ishidden);
	}

	public Integer getIshidden() {
		return getInt("ishidden");
	}

	public void setHiddenTime(java.util.Date hiddenTime) {
		set("hidden_time", hiddenTime);
	}

	public java.util.Date getHiddenTime() {
		return get("hidden_time");
	}

	public void setBatchId(String batchId) {
		set("batch_id", batchId);
	}

	public String getBatchId() {
		return getStr("batch_id");
	}

	public void setIsArchive(Integer isArchive) {
		set("is_archive", isArchive);
	}

	public Integer getIsArchive() {
		return getInt("is_archive");
	}

}
