package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseAdminUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminUserRole extends BaseAdminUserRole<AdminUserRole> {
	public static final AdminUserRole dao = new AdminUserRole().dao();

	private String userIds;

	public String getUserIds() {
		return userIds;
	}

	public void setUserIds(String userIds) {
		this.userIds = userIds;
	}

	private String roleIds;

	public String getRoleIds(){
		return roleIds;
	}

	public void setRoleIds(String roleIds){
		this.roleIds = roleIds;
	}
}
