package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseAdminRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminRoleMenu extends BaseAdminRoleMenu<AdminRoleMenu> {
	public static final AdminRoleMenu dao = new AdminRoleMenu().dao();
}
