package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseAdminFleldStyle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminFieldStyle extends BaseAdminFleldStyle<AdminFieldStyle> {
	public static final AdminFieldStyle dao = new AdminFieldStyle().dao();
}
