package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseAdminField;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminField extends BaseAdminField<AdminField> {
	public static final AdminField dao = new AdminField().dao();

	private Integer fieldType;
	private List<String> setting;

	public Integer getFieldType() {
		return fieldType;
	}

	public void setFieldType(Integer fieldType) {
		this.fieldType = fieldType;
	}

	public List<String> getSetting() {
		return setting;
	}

	public void setSetting(List<String> setting) {
		this.setting = setting;
	}
}
