package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseAdminExamineStep;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminExamineStep extends BaseAdminExamineStep<AdminExamineStep> {
	public static final AdminExamineStep dao = new AdminExamineStep().dao();
}
