package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseAdminFieldSort;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminFieldSort extends BaseAdminFieldSort<AdminFieldSort> {
	public static final AdminFieldSort dao = new AdminFieldSort().dao();

	private String hideIds;
	private String noHideIds;

	public String getHideIds() {
		return hideIds;
	}

	public void setHideIds(String hideIds) {
		this.hideIds = hideIds;
	}

	public String getNoHideIds() {
		return noHideIds;
	}

	public void setNoHideIds(String noHideIds) {
		this.noHideIds = noHideIds;
	}
}
