package com.kakarote.crm9.erp.admin.entity;


import com.kakarote.crm9.erp.admin.entity.base.BaseAdminMessage;

import java.util.HashMap;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminMessage extends BaseAdminMessage<AdminMessage> {
    public static final AdminMessage dao = new AdminMessage().dao();
    private static final Map<Integer, Integer[]> integerMap = new HashMap<>();
    private Integer label;

    public Integer getLabel() {
        return label;
    }

    public AdminMessage setLabel(Integer label) {
        this.label = label;
        super.put("types", integerMap.get(label));
        return this;
    }

    static {
        integerMap.put(0, new Integer[]{});
        integerMap.put(1, new Integer[]{1, 2, 3});
        integerMap.put(2, new Integer[]{4, 5});
        integerMap.put(3, new Integer[]{6, 7});
        integerMap.put(4, new Integer[]{8});
        integerMap.put(5, new Integer[]{9});
        integerMap.put(6, new Integer[]{10, 11, 12, 13, 22, 23, 24});
        integerMap.put(7, new Integer[]{14, 15, 16, 17, 18, 19, 20, 21});
    }
}
