package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseAdminDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminDept extends BaseAdminDept<AdminDept> {
	public static final AdminDept dao = new AdminDept().dao();
}
