package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseAdminMessage;
/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminMessage extends BaseAdminMessage<AdminMessage> {
    public static final AdminMessage dao = new AdminMessage().dao();
}
