package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseAdminScene;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminScene extends BaseAdminScene<AdminScene> {
	public static final AdminScene dao = new AdminScene().dao();
	private Integer isDefault;
	private String noHideIds;
	private String hideIds;

	public Integer getIsDefault() {
		return isDefault;
	}

	public void setIsDefault(Integer isDefault) {
		this.isDefault = isDefault;
	}

	public String getNoHideIds() {
		return noHideIds;
	}

	public void setNoHideIds(String noHideIds) {
		this.noHideIds = noHideIds;
	}

	public String getHideIds() {
		return hideIds;
	}

	public void setHideIds(String hideIds) {
		this.hideIds = hideIds;
	}
}
