package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseCrmBusinessType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmBusinessType extends BaseCrmBusinessType<CrmBusinessType> {
	public static final CrmBusinessType dao = new CrmBusinessType().dao();
}
