package com.kakarote.crm9.erp.work.entity;

import com.kakarote.crm9.erp.work.entity.base.BaseTaskComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskComment extends BaseTaskComment<TaskComment> {
	public static final TaskComment dao = new TaskComment().dao();
}
