package com.kakarote.crm9.erp.work.entity;

import com.kakarote.crm9.erp.work.entity.base.BaseWorkTaskLable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkTaskLable extends BaseWorkTaskLable<WorkTaskLable> {
	public static final WorkTaskLable dao = new WorkTaskLable().dao();
}
