package com.kakarote.crm9.erp.work.entity;

import com.kakarote.crm9.erp.work.entity.base.BaseWorkRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkRelation extends BaseWorkRelation<WorkRelation> {
	public static final WorkRelation dao = new WorkRelation().dao();
}
