package com.kakarote.crm9.erp.work.entity;

import com.kakarote.crm9.erp.work.entity.base.BaseWorkTaskClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkTaskClass extends BaseWorkTaskClass<WorkTaskClass> {
	public static final WorkTaskClass dao = new WorkTaskClass().dao();
}
