package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmActionRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmActionRecord extends BaseCrmActionRecord<CrmActionRecord> {
	public static final CrmActionRecord dao = new CrmActionRecord().dao();
}
