package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmBusiness;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmBusiness extends BaseCrmBusiness<CrmBusiness> {
	public static final CrmBusiness dao = new CrmBusiness().dao();
	//移出方式（1.移除2.转为团队成员）
	private Integer transferType;
	//权限（1.只读2.读写）
	private Integer power;
	private String ids;
	private Integer newOwnerUserId;
	private String memberIds;
	private Integer orderNum;
	private String businessIds;

	public Integer getTransferType() {
		return transferType;
	}

	public void setTransferType(Integer transferType) {
		this.transferType = transferType;
	}

	public Integer getPower() {
		return power;
	}

	public void setPower(Integer power) {
		this.power = power;
	}

	public String getIds() {
		return ids;
	}

	public void setIds(String ids) {
		this.ids = ids;
	}

	public String getMemberIds() {
		return memberIds;
	}

	public void setMemberIds(String memberIds) {
		this.memberIds = memberIds;
	}

	public Integer getOrderNum() {
		return orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	public Integer getNewOwnerUserId() {
		return newOwnerUserId;
	}

	public void setNewOwnerUserId(Integer newOwnerUserId) {
		this.newOwnerUserId = newOwnerUserId;
	}

	public String getBusinessIds() {
		return businessIds;
	}

	public void setBusinessIds(String businessIds) {
		this.businessIds = businessIds;
	}
}
