package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmContacts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmContacts extends BaseCrmContacts<CrmContacts> {
	public static final CrmContacts dao = new CrmContacts().dao();

	private String contactsIds;
	private Integer newOwnerUserId;

	public String getContactsIds() {
		return contactsIds;
	}

	public void setContactsIds(String contactsIds) {
		this.contactsIds = contactsIds;
	}

	public Integer getNewOwnerUserId() {
		return newOwnerUserId;
	}

	public void setNewOwnerUserId(Integer newOwnerUserId) {
		this.newOwnerUserId = newOwnerUserId;
	}
}
