package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmCustomerSetting;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmCustomerSetting extends BaseCrmCustomerSetting<CrmCustomerSetting> {
	public static final CrmCustomerSetting dao = new CrmCustomerSetting().dao();

	private List<Long> userList = new ArrayList<>();

	private List<Integer> deptList = new ArrayList<>();

	public List<Long> getUserList() {
		return userList;
	}

	public CrmCustomerSetting setUserList(List<Long> userList) {
		this.userList = userList;
		return this;
	}

	public List<Integer> getDeptList() {
		return deptList;
	}

	public CrmCustomerSetting setDeptList(List<Integer> deptList) {
		this.deptList = deptList;
		return this;
	}
}
