package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmCustomerStats;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmCustomerStats extends BaseCrmCustomerStats<CrmCustomerStats> {
	public static final CrmCustomerStats dao = new CrmCustomerStats().dao();
}
