package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmLeads;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmLeads extends BaseCrmLeads<CrmLeads> {
	public static final CrmLeads dao = new CrmLeads().dao();
}
