package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmProduct extends BaseCrmProduct<CrmProduct> {
	public static final CrmProduct dao = new CrmProduct().dao();
}
