package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmReceivables;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmReceivables extends BaseCrmReceivables<CrmReceivables> {
	public static final CrmReceivables dao = new CrmReceivables().dao();
}
