package com.kakarote.crm9.erp.oa.entity;

import com.kakarote.crm9.erp.oa.entity.base.BaseOaEvent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaEvent extends BaseOaEvent<OaEvent> {
	public static final OaEvent dao = new OaEvent().dao();

	private Integer isRepeat;
	private String customerIds;
	private String contactsIds;
	private String businessIds;
	private String contractIds;
	private Integer noticeType;
	private String repeat;

	public Integer getIsRepeat() {
		return isRepeat;
	}

	public void setIsRepeat(Integer isRepeat) {
		this.isRepeat = isRepeat;
	}

	public String getCustomerIds() {
		return customerIds;
	}

	public void setCustomerIds(String customerIds) {
		this.customerIds = customerIds;
	}

	public String getContactsIds() {
		return contactsIds;
	}

	public void setContactsIds(String contactsIds) {
		this.contactsIds = contactsIds;
	}

	public String getBusinessIds() {
		return businessIds;
	}

	public void setBusinessIds(String businessIds) {
		this.businessIds = businessIds;
	}

	public String getContractIds() {
		return contractIds;
	}

	public void setContractIds(String contractIds) {
		this.contractIds = contractIds;
	}

	public Integer getNoticeType() {
		return noticeType;
	}

	public void setNoticeType(Integer noticeType) {
		this.noticeType = noticeType;
	}

	public String getRepeat() {
		return repeat;
	}

	public void setRepeat(String repeat) {
		this.repeat = repeat;
	}
}
