package com.kakarote.crm9.erp.oa.entity;

import com.kakarote.crm9.erp.oa.entity.base.BaseOaEventNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaEventNotice extends BaseOaEventNotice<OaEventNotice> {
	public static final OaEventNotice dao = new OaEventNotice().dao();
}
