package com.kakarote.crm9.erp.oa.entity;

import com.kakarote.crm9.erp.oa.entity.base.BaseOaExamineRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaExamineRecord extends BaseOaExamineRecord<OaExamineRecord> {
	public static final OaExamineRecord dao = new OaExamineRecord().dao();
}
