package com.kakarote.crm9.erp.oa.entity;

import com.kakarote.crm9.erp.oa.entity.base.BaseOaExamineTravel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaExamineTravel extends BaseOaExamineTravel<OaExamineTravel> {
	public static final OaExamineTravel dao = new OaExamineTravel().dao();
}
