package com.kakarote.crm9.erp.oa.entity;

import com.kakarote.crm9.erp.oa.entity.base.BaseOaLogRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaLogRelation extends BaseOaLogRelation<OaLogRelation> {
	public static final OaLogRelation dao = new OaLogRelation().dao();
}
