package com.kakarote.crm9.erp.oa.entity;

import com.kakarote.crm9.erp.oa.entity.base.BaseOaLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaLog extends BaseOaLog<OaLog> {
	public static final OaLog dao = new OaLog().dao();
}
