package com.kakarote.crm9.erp.oa.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaActionRecord<M extends BaseOaActionRecord<M>> extends Model<M> implements IBean {

	public void setLogId(java.lang.Integer logId) {
		set("log_id", logId);
	}
	
	public java.lang.Integer getLogId() {
		return getInt("log_id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setActionId(java.lang.Integer actionId) {
		set("action_id", actionId);
	}
	
	public java.lang.Integer getActionId() {
		return getInt("action_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setJoinUserIds(java.lang.String joinUserIds) {
		set("join_user_ids", joinUserIds);
	}
	
	public java.lang.String getJoinUserIds() {
		return getStr("join_user_ids");
	}

	public void setDeptIds(java.lang.String deptIds) {
		set("dept_ids", deptIds);
	}
	
	public java.lang.String getDeptIds() {
		return getStr("dept_ids");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

}
