package com.kakarote.crm9.erp.oa.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaAnnouncement<M extends BaseOaAnnouncement<M>> extends Model<M> implements IBean {

	public void setAnnouncementId(Integer announcementId) {
		set("announcement_id", announcementId);
	}

	public Integer getAnnouncementId() {
		return getInt("announcement_id");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return getStr("title");
	}

	public void setContent(String content) {
		set("content", content);
	}

	public String getContent() {
		return getStr("content");
	}

	public void setCreateUserId(Integer createUserId) {
		set("create_user_id", createUserId);
	}

	public Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}

	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public void setDeptIds(String deptIds) {
		set("dept_ids", deptIds);
	}

	public String getDeptIds() {
		return getStr("dept_ids");
	}

	public void setOwnerUserIds(String ownerUserIds) {
		set("owner_user_ids", ownerUserIds);
	}

	public String getOwnerUserIds() {
		return getStr("owner_user_ids");
	}

	public void setReadUserIds(String readUserIds) {
		set("read_user_ids", readUserIds);
	}

	public String getReadUserIds() {
		return getStr("read_user_ids");
	}

}
