package com.kakarote.crm9.erp.oa.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaLog<M extends BaseOaLog<M>> extends Model<M> implements IBean {

	public void setLogId(java.lang.Integer logId) {
		set("log_id", logId);
	}
	
	public java.lang.Integer getLogId() {
		return getInt("log_id");
	}

	public void setCategoryId(java.lang.Integer categoryId) {
		set("category_id", categoryId);
	}
	
	public java.lang.Integer getCategoryId() {
		return getInt("category_id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setTomorrow(java.lang.String tomorrow) {
		set("tomorrow", tomorrow);
	}
	
	public java.lang.String getTomorrow() {
		return getStr("tomorrow");
	}

	public void setQuestion(java.lang.String question) {
		set("question", question);
	}
	
	public java.lang.String getQuestion() {
		return getStr("question");
	}

	public void setCreateUserId(java.lang.Long createUserId) {
		set("create_user_id", createUserId);
	}
	
	public java.lang.Long getCreateUserId() {
		return getLong("create_user_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setSendUserIds(java.lang.String sendUserIds) {
		set("send_user_ids", sendUserIds);
	}
	
	public java.lang.String getSendUserIds() {
		return getStr("send_user_ids");
	}

	public void setSendDeptIds(java.lang.String sendDeptIds) {
		set("send_dept_ids", sendDeptIds);
	}
	
	public java.lang.String getSendDeptIds() {
		return getStr("send_dept_ids");
	}

	public void setReadUserIds(java.lang.String readUserIds) {
		set("read_user_ids", readUserIds);
	}
	
	public java.lang.String getReadUserIds() {
		return getStr("read_user_ids");
	}

	public void setBatchId(java.lang.String batchId) {
		set("batch_id", batchId);
	}
	
	public java.lang.String getBatchId() {
		return getStr("batch_id");
	}

}
