package com.kakarote.crm9.erp.oa.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOaActionRecord<M extends BaseOaActionRecord<M>> extends Model<M> implements IBean {

	public M setLogId(Integer logId) {
		set("log_id", logId);
		return (M)this;
	}

	public Integer getLogId() {
		return getInt("log_id");
	}

	public M setUserId(Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public Integer getUserId() {
		return getInt("user_id");
	}



	public Integer getActionId() {
		return getInt("action_id");
	}

	public M setActionId(Integer actionId) {
		set("action_id", actionId);
		return (M)this;
	}

	public M setType(Integer type) {
		set("type", type);
		return (M)this;
	}

	public Integer getType() {
		return getInt("type");
	}

	public M setContent(String content) {
		set("content", content);
		return (M)this;
	}

	public String getContent() {
		return getStr("content");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setJoinUserIds(String joinUserIds) {
		set("join_user_ids", joinUserIds);
		return (M)this;
	}

	public String getJoinUserIds() {
		return getStr("join_user_ids");
	}

	public M setDeptIds(String deptIds) {
		set("dept_ids", deptIds);
		return (M)this;
	}

	public String getDeptIds() {
		return getStr("dept_ids");
	}

}
