package com.kakarote.crm9.erp.oa.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaEventNotice<M extends BaseOaEventNotice<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setEventId(Integer eventId) {
		set("event_id", eventId);
	}

	public Integer getEventId() {
		return getInt("event_id");
	}

	public void setNoticetype(String noticetype) {
		set("noticetype", noticetype);
	}

	public String getNoticetype() {
		return getStr("noticetype");
	}

	public void setRepeat(String repeat) {
		set("repeat", repeat);
	}

	public String getRepeat() {
		return getStr("repeat");
	}

	public void setStartTime(Integer startTime) {
		set("start_time", startTime);
	}

	public Integer getStartTime() {
		return getInt("start_time");
	}

	public void setStopTime(Integer stopTime) {
		set("stop_time", stopTime);
	}

	public Integer getStopTime() {
		return getInt("stop_time");
	}

}
