package com.kakarote.crm9.erp.oa.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOaExamine<M extends BaseOaExamine<M>> extends Model<M> implements IBean {

	public M setExamineId(Integer examineId) {
		set("examine_id", examineId);
		return (M)this;
	}

	public Integer getExamineId() {
		return getInt("examine_id");
	}

	public M setCategoryId(Integer categoryId) {
		set("category_id", categoryId);
		return (M)this;
	}

	public Integer getCategoryId() {
		return getInt("category_id");
	}

	public M setContent(String content) {
		set("content", content);
		return (M)this;
	}

	public String getContent() {
		return getStr("content");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

	public M setTypeId(String typeId) {
		set("type_id", typeId);
		return (M)this;
	}

	public String getTypeId() {
		return getStr("type_id");
	}

	public M setMoney(java.math.BigDecimal money) {
		set("money", money);
		return (M)this;
	}

	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	public M setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
		return (M)this;
	}

	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public M setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
		return (M)this;
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public M setDuration(java.math.BigDecimal duration) {
		set("duration", duration);
		return (M)this;
	}

	public java.math.BigDecimal getDuration() {
		return get("duration");
	}

	public M setCreateUserId(Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}

	public Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setBatchId(String batchId) {
		set("batch_id", batchId);
		return (M)this;
	}

	public String getBatchId() {
		return getStr("batch_id");
	}

}
