package com.kakarote.crm9.erp.oa.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaExamineTravel<M extends BaseOaExamineTravel<M>> extends Model<M> implements IBean {

	public void setTravelId(Integer travelId) {
		set("travel_id", travelId);
	}

	public Integer getTravelId() {
		return getInt("travel_id");
	}

	public void setExamineId(Integer examineId) {
		set("examine_id", examineId);
	}

	public Integer getExamineId() {
		return getInt("examine_id");
	}

	public void setStartAddress(String startAddress) {
		set("start_address", startAddress);
	}

	public String getStartAddress() {
		return getStr("start_address");
	}

	public void setStartTime(Date startTime) {
		set("start_time", startTime);
	}

	public Date getStartTime() {
		return getDate("start_time");
	}

	public void setEndAddress(String endAddress) {
		set("end_address", endAddress);
	}

	public String getEndAddress() {
		return getStr("end_address");
	}

	public void setEndTime(Date endTime) {
		set("end_time", endTime);
	}

	public Date getEndTime() {
		return getDate("end_time");
	}

	public void setTraffic(java.math.BigDecimal traffic) {
		set("traffic", traffic);
	}

	public java.math.BigDecimal getTraffic() {
		return get("traffic");
	}

	public void setStay(java.math.BigDecimal stay) {
		set("stay", stay);
	}

	public java.math.BigDecimal getStay() {
		return get("stay");
	}

	public void setDiet(java.math.BigDecimal diet) {
		set("diet", diet);
	}

	public java.math.BigDecimal getDiet() {
		return get("diet");
	}

	public void setOther(java.math.BigDecimal other) {
		set("other", other);
	}

	public java.math.BigDecimal getOther() {
		return get("other");
	}

	public void setMoney(java.math.BigDecimal money) {
		set("money", money);
	}

	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	public void setVehicle(String vehicle) {
		set("vehicle", vehicle);
	}

	public String getVehicle() {
		return getStr("vehicle");
	}

	public void setTrip(String trip) {
		set("trip", trip);
	}

	public String getTrip() {
		return getStr("trip");
	}

	public void setDuration(java.math.BigDecimal duration) {
		set("duration", duration);
	}

	public java.math.BigDecimal getDuration() {
		return get("duration");
	}

	public void setDescription(String description) {
		set("description", description);
	}

	public String getDescription() {
		return getStr("description");
	}

	public void setBatchId(String batchId) {
		set("batch_id", batchId);
	}

	public String getBatchId() {
		return getStr("batch_id");
	}

}
