package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminConfig<M extends BaseAdminConfig<M>> extends Model<M> implements IBean {

	public void setConfigId(Integer configId) {
		set("config_id", configId);
	}

	public Integer getConfigId() {
		return getInt("config_id");
	}

	public void setPid(Integer pid) {
		set("pid", pid);
	}

	public Integer getPid() {
		return getInt("pid");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return getStr("name");
	}

	public void setValue(String value) {
		set("value", value);
	}

	public String getValue() {
		return getStr("value");
	}

	public void setDescription(String description) {
		set("description", description);
	}

	public String getDescription() {
		return getStr("description");
	}

}
