package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminMessage<M extends BaseAdminMessage<M>> extends Model<M> implements IBean {

	public M setMessageId(Long messageId) {
		set("message_id", messageId);
		return (M)this;
	}

	public Long getMessageId() {
		return getLong("message_id");
	}

	public M setTitle(String title) {
		set("title", title);
		return (M)this;
	}

	public String getTitle() {
		return getStr("title");
	}

	public M setContent(String content) {
		set("content", content);
		return (M)this;
	}

	public String getContent() {
		return getStr("content");
	}

	public Integer getLabel() {
		return getInt("label");
	}

	public M setLabel(Integer label) {
		set("label",label);
		return (M)this;
	}

	public M setType(Integer type) {
		set("type", type);
		return (M)this;
	}

	public Integer getType() {
		return getInt("type");
	}

	public M setTypeId(Integer typeId) {
		set("type_id", typeId);
		return (M)this;
	}

	public Integer getTypeId() {
		return getInt("type_id");
	}

	public M setCreateUser(Long createUser) {
		set("create_user", createUser);
		return (M)this;
	}

	public Long getCreateUser() {
		return getLong("create_user");
	}

	public M setRecipientUser(Long recipientUser) {
		set("recipient_user", recipientUser);
		return (M)this;
	}

	public Long getRecipientUser() {
		return getLong("recipient_user");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setIsRead(Integer isRead) {
		set("is_read", isRead);
		return (M)this;
	}

	public Integer getIsRead() {
		return getInt("is_read");
	}

	public M setReadTime(java.util.Date readTime) {
		set("read_time", readTime);
		return (M)this;
	}

	public java.util.Date getReadTime() {
		return get("read_time");
	}
}
