package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminExamine<M extends BaseAdminExamine<M>> extends Model<M> implements IBean {

	public M setExamineId(Integer examineId) {
		set("examine_id", examineId);
		return (M)this;
	}

	public Integer getExamineId() {
		return getInt("examine_id");
	}

	public M setCategoryType(Integer categoryType) {
		set("category_type", categoryType);
		return (M)this;
	}

	public Integer getCategoryType() {
		return getInt("category_type");
	}

	public M setExamineType(Integer examineType) {
		set("examine_type", examineType);
		return (M)this;
	}

	public Integer getExamineType() {
		return getInt("examine_type");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setDeptIds(String deptIds) {
		set("dept_ids", deptIds);
		return (M)this;
	}

	public String getDeptIds() {
		return getStr("dept_ids");
	}

	public M setUserIds(String userIds) {
		set("user_ids", userIds);
		return (M)this;
	}

	public String getUserIds() {
		return getStr("user_ids");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setCreateUserId(Long createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}

	public Long getCreateUserId() {
		return getLong("create_user_id");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setUpdateUserId(Long updateUserId) {
		set("update_user_id", updateUserId);
		return (M)this;
	}

	public Long getUpdateUserId() {
		return getLong("update_user_id");
	}

	public M setStatus(Integer status) {
		set("status", status);
		return (M)this;
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public M setRemarks(String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public String getRemarks() {
		return getStr("remarks");
	}

}
