package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminRecord<M extends BaseAdminRecord<M>> extends Model<M> implements IBean {

	public void setRecordId(Integer recordId) {
		set("record_id", recordId);
	}

	public Integer getRecordId() {
		return getInt("record_id");
	}

	public void setTypes(String types) {
		set("types", types);
	}

	public String getTypes() {
		return getStr("types");
	}

	public void setTypesId(Integer typesId) {
		set("types_id", typesId);
	}

	public Integer getTypesId() {
		return getInt("types_id");
	}

	public void setContent(String content) {
		set("content", content);
	}

	public String getContent() {
		return getStr("content");
	}

	public void setCategory(String category) {
		set("category", category);
	}

	public String getCategory() {
		return get("category");
	}

	public void setNextTime(java.util.Date nextTime) {
		set("next_time", nextTime);
	}

	public java.util.Date getNextTime() {
		return get("next_time");
	}

	public void setBusinessIds(String businessIds) {
		set("business_ids", businessIds);
	}

	public String getBusinessIds() {
		return getStr("business_ids");
	}

	public void setContactsIds(String contactsIds) {
		set("contacts_ids", contactsIds);
	}

	public String getContactsIds() {
		return getStr("contacts_ids");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setCreateUserId(Integer createUserId) {
		set("create_user_id", createUserId);
	}

	public Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public void setBatchId(String batchId) {
		set("batch_id", batchId);
	}

	public String getBatchId() {
		return getStr("batch_id");
	}

}
