package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmBusinessStatus<M extends BaseCrmBusinessStatus<M>> extends Model<M> implements IBean {

	public void setStatusId(Integer statusId) {
		set("status_id", statusId);
	}

	public Integer getStatusId() {
		return getInt("status_id");
	}

	public void setTypeId(Integer typeId) {
		set("type_id", typeId);
	}

	public Integer getTypeId() {
		return getInt("type_id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return getStr("name");
	}

	public void setRate(String rate) {
		set("rate", rate);
	}

	public String getRate() {
		return getStr("rate");
	}

	public void setOrderNum(Integer orderNum) {
		set("order_num", orderNum);
	}

	public Integer getOrderNum() {
		return getInt("order_num");
	}

}
