package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminExamine<M extends BaseAdminExamine<M>> extends Model<M> implements IBean {

	public void setExamineId(java.lang.Integer examineId) {
		set("examine_id", examineId);
	}
	
	public java.lang.Integer getExamineId() {
		return getInt("examine_id");
	}

	public void setCategoryType(java.lang.Integer categoryType) {
		set("category_type", categoryType);
	}
	
	public java.lang.Integer getCategoryType() {
		return getInt("category_type");
	}

	public void setExamineType(java.lang.Integer examineType) {
		set("examine_type", examineType);
	}
	
	public java.lang.Integer getExamineType() {
		return getInt("examine_type");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setDeptIds(java.lang.String deptIds) {
		set("dept_ids", deptIds);
	}
	
	public java.lang.String getDeptIds() {
		return getStr("dept_ids");
	}

	public void setUserIds(java.lang.String userIds) {
		set("user_ids", userIds);
	}
	
	public java.lang.String getUserIds() {
		return getStr("user_ids");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUserId(java.lang.Long createUserId) {
		set("create_user_id", createUserId);
	}
	
	public java.lang.Long getCreateUserId() {
		return getLong("create_user_id");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateUserId(java.lang.Long updateUserId) {
		set("update_user_id", updateUserId);
	}
	
	public java.lang.Long getUpdateUserId() {
		return getLong("update_user_id");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

}
