package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminUser<M extends BaseAdminUser<M>> extends Model<M> implements IBean {

	public void setUserId(Long userId) {
		set("user_id", userId);
	}

	public Long getUserId() {
		return getLong("user_id");
	}

	public void setUsername(String username) {
		set("username", username);
	}

	public String getUsername() {
		return getStr("username");
	}

	public void setPassword(String password) {
		set("password", password);
	}

	public String getPassword() {
		return getStr("password");
	}

	public void setSalt(String salt) {
		set("salt", salt);
	}

	public String getSalt() {
		return getStr("salt");
	}

	public void setImg(String img) {
		set("img", img);
	}

	public String getImg() {
		return getStr("img");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setRealname(String realname) {
		set("realname", realname);
	}

	public String getRealname() {
		return getStr("realname");
	}

	public void setNum(String num) {
		set("num", num);
	}

	public String getNum() {
		return getStr("num");
	}

	public void setMobile(String mobile) {
		set("mobile", mobile);
	}

	public String getMobile() {
		return getStr("mobile");
	}

	public void setEmail(String email) {
		set("email", email);
	}

	public String getEmail() {
		return getStr("email");
	}

	public void setSex(Integer sex) {
		set("sex", sex);
	}

	public Integer getSex() {
		return getInt("sex");
	}

	public void setDeptId(Integer deptId) {
		set("dept_id", deptId);
	}

	public Integer getDeptId() {
		return getInt("dept_id");
	}

	public void setPost(String post) {
		set("post", post);
	}

	public String getPost() {
		return getStr("post");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public void setParentId(Long parentId) {
		set("parent_id", parentId);
	}

	public Long getParentId() {
		return getLong("parent_id");
	}

	public void setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}

	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}

	public void setLastLoginIp(String lastLoginIp) {
		set("last_login_ip", lastLoginIp);
	}

	public String getLastLoginIp() {
		return getStr("last_login_ip");
	}

}
