package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminMessage<M extends BaseAdminMessage<M>> extends Model<M> implements IBean {

	public void setMessageId(Long messageId) {
		set("message_id", messageId);
	}

	public Long getMessageId() {
		return getLong("message_id");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return getStr("title");
	}

	public void setContent(String content) {
		set("content", content);
	}

	public String getContent() {
		return getStr("content");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return getInt("type");
	}

	public void setTypeId(Integer typeId) {
		set("type_id", typeId);
	}

	public Integer getTypeId() {
		return getInt("type_id");
	}

	public void setCreateUser(Long createUser) {
		set("create_user", createUser);
	}

	public Long getCreateUser() {
		return getLong("create_user");
	}

	public void setRecipientUser(Long recipientUser) {
		set("recipient_user", recipientUser);
	}

	public Long getRecipientUser() {
		return getLong("recipient_user");
	}

	public void setCreateTime(Date createTime) {
		set("create_time", createTime);
	}

	public Date getCreateTime() {
		return getDate("create_time");
	}

	public void setIsRead(Integer isRead) {
		set("is_read", isRead);
	}

	public Integer getIsRead() {
		return getInt("is_read");
	}

	public void setReadTime(Date readTime) {
		set("read_time", readTime);
	}

	public Date getReadTime() {
		return getDate("read_time");
	}

}
