package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminFile<M extends BaseAdminFile<M>> extends Model<M> implements IBean {

	public void setFileId(Integer fileId) {
		set("file_id", fileId);
	}

	public Integer getFileId() {
		return getInt("file_id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return getStr("name");
	}

	public void setSize(Long size) {
		set("size", size);
	}

	public String getSize() {
		return getStr("size");
	}

	public void setCreateUserId(Integer createUserId) {
		set("create_user_id", createUserId);
	}

	public Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setFilePath(String filePath) {
		set("file_path", filePath);
	}

	public String getFilePath() {
		return getStr("file_path");
	}

    public void setPath(String path) {
        set("path", path);
    }

    public String getPath() {
        return getStr("path");
    }

	public void setBatchId(String batchId) {
		set("batch_id", batchId);
	}

	public String getBatchId() {
		return getStr("batch_id");
	}

	public void setFileType(String fileType) {
		set("file_type", fileType);
	}

	public String getFileType() {
		return getStr("file_type");
	}

}
