package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmBusinessStatus<M extends BaseCrmBusinessStatus<M>> extends Model<M> implements IBean {

	public void setStatusId(java.lang.Integer statusId) {
		set("status_id", statusId);
	}
	
	public java.lang.Integer getStatusId() {
		return getInt("status_id");
	}

	public void setTypeId(java.lang.Integer typeId) {
		set("type_id", typeId);
	}
	
	public java.lang.Integer getTypeId() {
		return getInt("type_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setRate(java.lang.String rate) {
		set("rate", rate);
	}
	
	public java.lang.String getRate() {
		return getStr("rate");
	}

	public void setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
	}
	
	public java.lang.Integer getOrderNum() {
		return getInt("order_num");
	}

}
