package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminScene<M extends BaseAdminScene<M>> extends Model<M> implements IBean {

	public BaseAdminScene setSceneId(java.lang.Integer sceneId) {
		set("scene_id", sceneId);
		return this;
	}
	
	public java.lang.Integer getSceneId() {
		return getInt("scene_id");
	}

	public BaseAdminScene setType(java.lang.Integer type) {
		set("type", type);
		return this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public BaseAdminScene setName(java.lang.String name) {
		set("name", name);
		return this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public BaseAdminScene setUserId(java.lang.Long userId) {
		set("user_id", userId);
		return this;
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public BaseAdminScene setSort(java.lang.Integer sort) {
		set("sort", sort);
		return this;
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public BaseAdminScene setData(java.lang.String data) {
		set("data", data);
		return this;
	}
	
	public java.lang.String getData() {
		return getStr("data");
	}

	public BaseAdminScene setIsHide(java.lang.Integer isHide) {
		set("is_hide", isHide);
		return this;
	}
	
	public java.lang.Integer getIsHide() {
		return getInt("is_hide");
	}

	public BaseAdminScene setIsSystem(java.lang.Integer isSystem) {
		set("is_system", isSystem);
		return this;
	}
	
	public java.lang.Integer getIsSystem() {
		return getInt("is_system");
	}

	public BaseAdminScene setBydata(java.lang.String bydata) {
		set("bydata", bydata);
		return this;
	}
	
	public java.lang.String getBydata() {
		return getStr("bydata");
	}

	public BaseAdminScene setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public BaseAdminScene setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
