package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminRole<M extends BaseAdminRole<M>> extends Model<M> implements IBean {

	public void setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
	}
	
	public java.lang.Integer getRoleId() {
		return getInt("role_id");
	}

	public void setRoleName(java.lang.String roleName) {
		set("role_name", roleName);
	}
	
	public java.lang.String getRoleName() {
		return getStr("role_name");
	}

	public void setRoleType(java.lang.Integer roleType) {
		set("role_type", roleType);
	}
	
	public java.lang.Integer getRoleType() {
		return getInt("role_type");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setDataType(java.lang.Integer dataType) {
		set("data_type", dataType);
	}
	
	public java.lang.Integer getDataType() {
		return getInt("data_type");
	}

	public void setIsHidden(java.lang.Integer isHidden) {
		set("is_hidden", isHidden);
	}
	
	public java.lang.Integer getIsHidden() {
		return getInt("is_hidden");
	}

	public void setLabel(java.lang.Integer label) {
		set("label", label);
	}
	
	public java.lang.Integer getLabel() {
		return getInt("label");
	}

}
