package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminMenu<M extends BaseAdminMenu<M>> extends Model<M> implements IBean {

	public void setMenuId(java.lang.Integer menuId) {
		set("menu_id", menuId);
	}
	
	public java.lang.Integer getMenuId() {
		return getInt("menu_id");
	}

	public void setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
	}
	
	public java.lang.Long getParentId() {
		return getLong("parent_id");
	}

	public void setMenuName(java.lang.String menuName) {
		set("menu_name", menuName);
	}
	
	public java.lang.String getMenuName() {
		return getStr("menu_name");
	}

	public void setRealm(java.lang.String realm) {
		set("realm", realm);
	}
	
	public java.lang.String getRealm() {
		return getStr("realm");
	}

	public void setMenuType(java.lang.Integer menuType) {
		set("menu_type", menuType);
	}
	
	public java.lang.Integer getMenuType() {
		return getInt("menu_type");
	}

	public void setSort(java.lang.Long sort) {
		set("sort", sort);
	}
	
	public java.lang.Long getSort() {
		return getLong("sort");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

}
