package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminSceneDefault<M extends BaseAdminSceneDefault<M>> extends Model<M> implements IBean {

	public M setDefaultId(Integer defaultId) {
		set("default_id", defaultId);
		return (M)this;
	}

	public Integer getDefaultId() {
		return getInt("default_id");
	}

	public M setType(Integer type) {
		set("type", type);
		return (M)this;
	}

	public Integer getType() {
		return getInt("type");
	}

	public M setUserId(Long userId) {
		set("user_id", userId);
		return (M)this;
	}

	public Long getUserId() {
		return getLong("user_id");
	}

	public M setSceneId(Integer sceneId) {
		set("scene_id", sceneId);
		return (M)this;
	}

	public Integer getSceneId() {
		return getInt("scene_id");
	}

}
